PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX fhir: <http://hl7.org/fhir/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?patient (COUNT(distinct ?encounter) AS ?encounters) where {

?condition a fhir:Condition .
    ?condition fhir:Condition.subject [fhir:link ?patient ;].
    ?condition fhir:Condition.code [
        fhir:CodeableConcept.coding [
        fhir:index ?index;
        fhir:Coding.code [fhir:value ?codingCode] ;
        fhir:Coding.system [fhir:value ?codingSystem] ;
        fhir:Coding.display [fhir:value ?codingDisplay];
        ]
    ].
    
     FILTER (?codingSystem = "http://snomed.info/sct" && 
     ?codingCode in ("840546002"	,
					"103001002"	,
					"11833005"	,
					"267036007"	,
					"28743005"	,
					"36955009"	,
					"426000000"	,
					"44169009"	,
					"49727002"	,
					"135883003"	,
					"161855003"	,
					"161939006"	,
					"161940008"	,
					"161941007"	,
					"2237002"	,
					"23141003"	,
					"247410004"	,
					"274640006"	,
					"274664007"	,
					"284523002"	,
					"386661006"	,
					"409702008"	,
					"426976009"	,
					"43724002"	,
					"60845006"	,
					"75483001"	))

    ?condition fhir:Condition.onsetDateTime [
    	fhir:value ?onsetDateTime 
    ] .
    
    FILTER (YEAR(?onsetDateTime) >=2020 && 
        MONTH(?onsetDateTime) >= 1 &&
        DAY(?onsetDateTime) >=1) 
    
   	?condition fhir:Condition.encounter [
		fhir:link ?encounter
	] . 
}GROUP BY ?patient HAVING (?encounters > 1)
